name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: |
        # Create a simple vite config for GitHub build
        cat > vite.config.github.js << 'EOF'
        import { defineConfig } from "vite";
        import react from "@vitejs/plugin-react";
        import path from "path";
        
        export default defineConfig({
          plugins: [react()],
          root: "./client",
          build: {
            outDir: "../dist",
            emptyOutDir: true,
          },
          resolve: {
            alias: {
              "@": path.resolve("./client/src"),
              "@shared": path.resolve("./shared"),
            },
          },
        });
        EOF
        # Build with the GitHub-specific config
        npx vite build --config vite.config.github.js

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set permissions for gradlew
      run: chmod +x android/gradlew

    - name: Build debug APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoBudget-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Create release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: CoBudget v${{ github.run_number }}
        files: android/app/build/outputs/apk/debug/app-debug.apk
        body: |
          CoBudget Android APK - Debug Build
          
          Install instructions:
          1. Enable "Install unknown apps" in Android Settings
          2. Download and tap the APK file to install
          3. Login with your Google account to start tracking expenses
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
